version: '3'
services:
  influxdb:
    environment:
      - INFLUXDB_DB=first
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    build:
      context: .
      dockerfile: Dockerfile.influxdb
    ports:
      - "8086:8086"
  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    links:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - "3000:3000"
  Jmeter:
    image: ustb4/jmeter
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/jmeter
    command: 'version'