name: Jmeter - Performance Web App Tests

env:
  PROJECT_LOCATION: ${{ github.workspace }}

on:
    schedule:
        -   cron: '30 21 * * *'
    workflow_dispatch:
        inputs:
            tags:
                description: 'Tags'
                required: false
                default: 'jmeter'

jobs:
  action_build:
    if: github.event_name != 'schedule'
    name: Manual - Execute JMeter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: jmeter-scripts/ModusCreate_Web_App_Jmeter_Script.jmx
          outputReportsFolder: reports/
          args: "--loglevel DEBUG"

      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/